import type { Metadata } from "next";
import { Inter, Montserrat, Poppins } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const mont = Montserrat({
  subsets: ["latin"],
  variable: "--font-serif",
});

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${mont.variable} ${poppins.variable}`} lang="en">
      <body >{children}</body>
    </html>
  );
}
